// Trusted domains for external redirects (no warning message)

export const TRUSTED_DOMAINS = [
	// retailers
	'amazon.com',
	'rei.com',
	'backcountry.com',
	'moosejaw.com',
	'campsaver.com',
	'steepandcheap.com',
	'evo.com',

	// Outdoor Brands
	'patagonia.com',
	'cotopaxi.com',
	'arcteryx.com',
	'thenorthface.com',
	'mammut.com',
	'prana.com',
	'kuhl.com',
	'smartwool.com',
	'icebreaker.com',
	'merrell.com',
	'salomon.com',
	'lowa.com',
	'scarpa.com',
	'lasportiva.com',
	'blackdiamond.com',
	'petzl.com',
	'mammut.com',

	// backpacking/hiking brands
	'osprey.com',
	'deuter.com',
	'hyperlitemountaingear.com',
	'zpacks.com',
	'gossamer-gear.com',
	'sixmoondesigns.com',
	'ula-equipment.com',
	'granite-gear.com',
	'gregorypacks.com',
	'kelty.com',
	'mountainhardwear.com',
	'nemo.com',
	'bigagnes.com',
	'msr.com',

	// ultralight
	'garagegrowngear.com',
	'hyperlitemountaingear.com',
	'tarptent.com',
	'enlightenedequipment.com',
	'katabaticgear.com',
	'westernmountaineering.com',
	'featheredfriends.com',
	'nunatak.com',
	'mountainlaureldesigns.com',
	'yamamountaingear.com',
	'salkadesigns.com',

	// european
	'decathlon.com',
	'cumulus.equipment',
	'atompacks.co.uk',

	// misc gear brands
	'darn-tough.com',
	'balega.com',
	'injinji.com',
	'wigwam.com',
	'farm-to-feet.com',
	'katadyn.com',
	'sawyer.com',
	'platypus.com',
	'nalgene.com',
	'kleankanteen.com',
	'grayl.com',
	'ursack.com',
	'farmtosummit.com',
	'jetboil.com',
	'snow-peak.com',
	'toaks.com',

	// Social/Content Platforms
	'youtube.com',
	'instagram.com',
	'reddit.com',
	'facebook.com',
	'twitter.com',
	'tiktok.com',
	'vimeo.com',

	// trip planning & outdoor resources
	'alltrails.com',
	'lighterpack.com',
	'outdoorgearlab.com',
	'caltopo.com',
	'guthook.com',
	'farout.io',
	'outdoorproject.com',
	'mountainproject.com',
	'peakbagger.com',
	'summitpost.org',
	'14ers.com',
	'hikingproject.com',
	'recreation.gov',
	'nps.gov',
	'fs.usda.gov',
	'blm.gov',
];
